services:
  loki:
    image: grafana/loki:2.9.0
    command: -config.file=/etc/loki/config.yml
    volumes:
      - ./monitoring/loki-config.yml:/etc/loki/config.yml:ro
      - loki_data:/loki
    restart: unless-stopped

  promtail:
    image: grafana/promtail:2.9.0
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./monitoring/promtail-config.yml:/etc/promtail/config.yml:ro
      - promtail_positions:/positions    # writable positions file
    restart: unless-stopped
    depends_on: [loki]

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    command:
      - --docker_only
      - --housekeeping_interval=30s
      - --store_container_labels=true
    # Docker Desktop–safe mounts (NO /rootfs and NO /var/lib/docker)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.53.0
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=3d
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/alerts.yml:/etc/prometheus/alerts.yml:ro
      - prometheus_data:/prometheus
    restart: unless-stopped
    depends_on: [cadvisor]

  grafana:
    image: grafana/grafana-oss:10.4.0
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=changeme
      - GF_SERVER_ROOT_URL=https://grafana.local.test
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`grafana.local.test`)
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.tls=true
      - traefik.http.services.grafana.loadbalancer.server.port=3000
    restart: unless-stopped
    depends_on: [prometheus, loki]

  blackbox:
    image: prom/blackbox-exporter:v0.25.0
    command: ["--config.file=/etc/blackbox/blackbox.yml"]
    volumes:
      - ./monitoring/blackbox.yml:/etc/blackbox/blackbox.yml:ro
    restart: unless-stopped

volumes:
  loki_data:
  prometheus_data:
  grafana_data:
  promtail_positions:
